version: "2"
services:

  yapi-srv:
    image: yapi-svr
    container_name: yapi-srv
    privileged: true
    restart: always
    ports:
      - "8000:3000"
    volumes:
      - ./config.json:/app/config.json
      - ./yapi-runtime:/app/runtime
        
networks:
  default:
    external:
      name: yapi-net
  
