version: "2"
services:

  yapi-srv:
    image: 172.25.2.140/anjubao-devops/yapi-svr
    container_name: yapi-srv
    privileged: true
    restart: always
    ports:
      - "8000:3000"
    networks:
      - yapi-net
    volumes:
      - ./config.json:/app/config.json
      - ./yapi-runtime:/app/runtime

        
networks:
  yapi-net:
    ipam:
        config:
            - subnet: 10.10.1.0/24
  
