version: "2"
services:
  mongo:
    image: mongo:3.4
    container_name: mongo
    privileged: true
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=anjubao
      - MONGO_INITDB_ROOT_PASSWORD=Anjubao1234
      
    volumes:
      - ./mongo-data:/data/db

networks:
  default:
    external:
      name: yapi-net
  
